# %% [markdown]
# ### 1. Setup & Authentication
import os
import json
import pandas as pd
from google.cloud import aiplatform, storage
from dotenv import load_dotenv

# Load your specific environment
load_dotenv("/home/npersson/.env")

PROJECT_ID = "gen-lang-client-0636424847"
LOCATION = "global"

aiplatform.init(project=PROJECT_ID, location=LOCATION)
storage_client = storage.Client(project=PROJECT_ID)

# %% [markdown]
# ### 2. List Recent Batch Jobs
# Use this to find the `JOB_ID` or `job_display_name` of the failed run.
jobs = aiplatform.BatchPredictionJob.list(order_by="create_time desc")

print(f"{'Display Name':<40} | {'Status':<15} | {'Resource Name'}")
print("-" * 100)
for job in jobs[:10]: # Look at last 10
    print(f"{job.display_name:<40} | {job.state.name:<15} | {job.resource_name}")

# %% [markdown]
# ### 3. Retrieve and Fix Parser
# Replace 'YOUR_JOB_ID_HERE' with the ID from the list above (e.g., '1234567890')
JOB_ID = "5781147476450869248"
job = aiplatform.BatchPredictionJob(f"projects/{PROJECT_ID}/locations/{LOCATION}/batchPredictionJobs/{JOB_ID}")
gcs_output_directory = job.output_info.gcs_output_directory
print(f"Fetching results from: {gcs_output_directory}")

bucket_name = gcs_output_directory.split('/')[2]
prefix = '/'.join(gcs_output_directory.split('/')[3:])
bucket = storage_client.bucket(bucket_name)
blobs = bucket.list_blobs(prefix=prefix)

all_flat_results = []

for blob in blobs:
    # Vertex names output files usually as 'prediction.results-00000-of-00001'
    if "predictions" in blob.name:
        print(f"Processing: {blob.name}")
        content = blob.download_as_text()
        
        for line in content.splitlines():
            if not line.strip(): continue
            
            record = json.loads(line)
            
            # NAVIGATION: Vertex Batch Gemini Output structure
            # Typically: record['response']['candidates'][0]['content']['parts'][0]['text']
            # OR: record['prediction'][...depending on SDK version]
            try:
                # 1. Try to find the raw text response
                response_obj = record.get('response') or record.get('prediction')
                if not response_obj:
                    continue
                    
                raw_text = response_obj['candidates'][0]['content']['parts'][0]['text']
                
                # 2. Parse the inner JSON string generated by the model
                parsed_json = json.loads(raw_text)
                
                if "results" in parsed_json:
                    all_flat_results.extend(parsed_json["results"])
                else:
                    # If the model returned a single object instead of a list
                    all_flat_results.append(parsed_json)
                    
            except (KeyError, IndexError, json.JSONDecodeError) as e:
                print(f"Skipping line due to error: {e}")
                # Optional: print(line) to see the exact structure
                

print(f"Successfully retrieved {len(all_flat_results)} records.")
# Preview
df_results = pd.DataFrame(all_flat_results)

# %% [markdown]
# ### 4. Re-merge with Source Data (Optional)
# If you have the original CSV path, run this to verify the merge logic.
# SOURCE_CSV = "path/to/your/input.tsv"
# df_source = pd.read_csv(SOURCE_CSV, sep="\t")
# df_source['index'] = df_source.index
# final_df = df_results.merge(df_source, on='index', how='left')
# display(final_df.head())